# -*- coding: utf-8 -*-
"""transformermodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mk7dMEG5_Od0IdxtASRwP-oeK9wSG-LZ
"""

!pip install transformers datasets torch torchtext scikit-learn pandas numpy matplotlib seaborn emoji
!pip install indic-nlp-library
!pip install googletrans==4.0.0-rc1
!pip install sentencepiece

# Step 2: Mount Google Drive and import libraries
import pandas as pd
import numpy as np
import re
import os
import warnings
warnings.filterwarnings('ignore')
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Step 3: Set paths and load dataset
base_path = "/content/drive/MyDrive/DATASET/4750858/DravidianCodeMix-2020/DravidianCodeMix"

# Let's first explore what files are available
import os

print("Files in dataset directory:")
for root, dirs, files in os.walk(base_path):
    for file in files:
        print(os.path.join(root, file))

tamil_files = []

for root, dirs, files in os.walk(base_path):
    for file in files:
        if 'tamil' in file.lower() or 'ta' in file.lower():
            full_path = os.path.join(root, file)
            tamil_files.append(full_path)
            print(f"Found Tamil file: {full_path}")

tamil_dfs = []
for file in tamil_files:
    try:
        # Try different encodings
        for encoding in ['utf-8', 'latin-1', 'iso-8859-1']:
            try:
                if file.endswith('.tsv'):
                    df = pd.read_csv(file, sep='\t', encoding=encoding)
                elif file.endswith('.csv'):
                    df = pd.read_csv(file, encoding=encoding)
                else:
                    continue
                print(f"Successfully loaded {file} with {encoding} encoding, shape: {df.shape}")
                # Add filename as column for tracking
                df['source_file'] = os.path.basename(file)
                tamil_dfs.append(df)
                break
            except:
                continue
    except Exception as e:
        print(f"Failed to load {file}: {e}")

if not tamil_dfs:
    print("Searching for all text files...")
    all_files = []
    for root, dirs, files in os.walk(base_path):
        for file in files:
            if file.endswith(('.tsv', '.csv', '.txt')):
                all_files.append(os.path.join(root, file))

    for file in all_files[:5]:  # Try first 5 files
        try:
            if file.endswith('.tsv'):
                df = pd.read_csv(file, sep='\t', encoding='utf-8', on_bad_lines='skip')
            elif file.endswith('.csv'):
                df = pd.read_csv(file, encoding='utf-8', on_bad_lines='skip')
            else:
                continue
            print(f"Loaded {file}, shape: {df.shape}")
            print(f"Columns: {df.columns.tolist()}")
            print(f"First few rows:\n{df.head()}")
            print("-" * 50)
            df['source_file'] = os.path.basename(file)
            tamil_dfs.append(df)
        except Exception as e:
            print(f"Failed to load {file}: {e}")

base_path = "/content/drive/MyDrive/DATASET/4750858/DravidianCodeMix-2020/DravidianCodeMix"

print("Looking for Tamil dataset files...")

# Let's first find all possible files
all_files = []
for root, dirs, files in os.walk(base_path):
    for file in files:
        if file.endswith(('.tsv', '.csv', '.txt', '.xlsx')):
            all_files.append(os.path.join(root, file))

print(f"Found {len(all_files)} files total")

# Try to find Tamil-specific files
tamil_keywords = ['tamil', 'ta', 'dravidian', 'codemix', 'sentiment']
tamil_files = []

for file in all_files:
    file_lower = file.lower()
    if any(keyword in file_lower for keyword in tamil_keywords):
        tamil_files.append(file)

print(f"\nFound {len(tamil_files)} potential Tamil files:")
for file in tamil_files[:10]:  # Show first 10
    print(f"  - {file}")

# Step 4: Load and inspect the files
all_dfs = []

for file in tamil_files:
    try:
        print(f"\nTrying to load: {file}")

        # Determine file type and load
        if file.endswith('.tsv'):
            # Try different separators and encodings
            for sep in ['\t', ',', ';']:
                for encoding in ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']:
                    try:
                        df = pd.read_csv(file, sep=sep, encoding=encoding, on_bad_lines='skip', engine='python')
                        if len(df.columns) > 1:  # Good dataframe
                            print(f"  Success with sep='{sep}', encoding='{encoding}', shape: {df.shape}")
                            break
                    except:
                        continue
                if 'df' in locals() and len(df.columns) > 1:
                    break

        elif file.endswith('.csv'):
            for encoding in ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']:
                try:
                    df = pd.read_csv(file, encoding=encoding, on_bad_lines='skip')
                    print(f"  Success with encoding='{encoding}', shape: {df.shape}")
                    break
                except:
                    continue

        elif file.endswith('.txt'):
            # Try to read as tsv/csv
            for sep in ['\t', ',', ';', '|']:
                try:
                    df = pd.read_csv(file, sep=sep, encoding='utf-8', on_bad_lines='skip', engine='python')
                    if len(df.columns) > 1:
                        print(f"  Success with sep='{sep}', shape: {df.shape}")
                        break
                except:
                    continue

        # If df loaded successfully
        if 'df' in locals() and len(df.columns) > 1:
            print(f"  Columns: {df.columns.tolist()}")
            print(f"  First few rows:")
            print(df.head(3))
            print(f"  Dtypes: {df.dtypes.to_dict()}")

            # Add filename and store
            df['source_file'] = os.path.basename(file)
            all_dfs.append(df)

            # Clean up
            del df

    except Exception as e:
        print(f"  Error loading {file}: {str(e)[:100]}")

# Step 5: Handle the case if no files were loaded
if not all_dfs:
    print("\nNo files loaded automatically. Let's manually inspect and load...")

    # Let's check one file in detail
    sample_file = None
    for file in tamil_files[:1]:
        sample_file = file
        break

    if sample_file:
        print(f"\nManually inspecting: {sample_file}")

        # Read raw content
        with open(sample_file, 'rb') as f:
            raw_content = f.read(1000)  # Read first 1000 bytes

        print("Raw content (first 1000 bytes):")
        print(raw_content)

        # Try to decode with different encodings
        for encoding in ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']:
            try:
                decoded = raw_content.decode(encoding)
                print(f"\nDecoded with {encoding}:")
                print(decoded[:500])

                # Try to parse as TSV
                lines = decoded.split('\n')
                for i, line in enumerate(lines[:5]):
                    print(f"Line {i}: {repr(line)}")
                    parts = line.split('\t')
                    print(f"  Split into {len(parts)} parts")
                    if len(parts) >= 2:
                        print(f"  Part 1 (text): {parts[0][:50]}")
                        print(f"  Part 2 (label): {parts[1]}")

                break
            except:
                continue

# Step 6: Manual dataset creation based on DravidianCodeMix format
print("\n" + "="*80)
print("MANUAL DATASET CREATION")
print("="*80)

# Based on DravidianCodeMix format, let's create our dataset
# The format is typically: text<TAB>label<TAB>other_info

# Let's create a robust loading function
def load_dravidian_dataset(filepath):
    """Load DravidianCodeMix dataset files"""
    data = []

    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Split by tab (common format)
        parts = line.split('\t')

        if len(parts) >= 2:
            # Usually format: text \t label \t [optional metadata]
            text = parts[0].strip()
            label = parts[1].strip()

            # Clean label (remove quotes, extra spaces)
            label = label.replace('"', '').replace("'", "").strip()

            # Standardize labels
            label_lower = label.lower()
            if 'positive' in label_lower or 'pos' in label_lower:
                clean_label = 'positive'
            elif 'negative' in label_lower or 'neg' in label_lower:
                clean_label = 'negative'
            elif 'neutral' in label_lower or 'neu' in label_lower or 'mixed' in label_lower:
                clean_label = 'neutral'
            elif 'not_offensive' in label_lower or 'not offensive' in label_lower:
                clean_label = 'neutral'
            elif 'offensive' in label_lower:
                clean_label = 'negative'
            else:
                clean_label = label_lower  # Keep as is

            data.append({'text': text, 'label': clean_label})

    return pd.DataFrame(data)

# Try loading with our custom function
tamil_dataframes = []

for file in tamil_files[:3]:  # Try first 3 files
    try:
        print(f"\nLoading {file} with custom function...")
        df = load_dravidian_dataset(file)
        print(f"  Loaded {len(df)} samples")
        print(f"  Label distribution:")
        print(df['label'].value_counts())

        if len(df) > 0:
            df['source_file'] = os.path.basename(file)
            tamil_dataframes.append(df)

            # Show samples
            print("  Sample data:")
            for i in range(min(3, len(df))):
                print(f"    Text: {df.iloc[i]['text'][:60]}...")
                print(f"    Label: {df.iloc[i]['label']}")
                print("    ---")
    except Exception as e:
        print(f"  Error: {e}")

if tamil_dataframes:
    # Combine all dataframes
    combined_df = pd.concat(tamil_dataframes, ignore_index=True)

    print(f"\nCombined dataset shape: {combined_df.shape}")
    print(f"Columns: {combined_df.columns.tolist()}")
    print(f"\nLabel distribution:")
    print(combined_df['label'].value_counts())

    # Create clean_df
    clean_df = combined_df[['text', 'label']].copy()

    # Remove duplicates and NaN
    clean_df = clean_df.dropna().drop_duplicates()
    clean_df = clean_df[clean_df['text'].astype(str).str.strip() != '']
    clean_df = clean_df[clean_df['label'].astype(str).str.strip() != '']

    print(f"\nCleaned dataset shape: {clean_df.shape}")

    # Show samples
    print("\nSample data from cleaned dataset:")
    for i in range(min(5, len(clean_df))):
        text = str(clean_df.iloc[i]['text'])
        label = str(clean_df.iloc[i]['label'])
        print(f"Sample {i+1}:")
        print(f"  Text: {text[:80]}..." if len(text) > 80 else f"  Text: {text}")
        print(f"  Label: {label}")
        print("-" * 50)

else:
    # Create synthetic dataset for demonstration
    print("\nCreating synthetic dataset for demonstration purposes...")

    synthetic_data = {
        'text': [
            "Romba nalla padam! Superb acting by Vijay 😍 #Master",
            "Movie was okay, but could have been better 🤔",
            "Waste of time and money! Very disappointing 😠",
            "Excellent direction! Thalapathy rocks! 🔥",
            "Not bad, but expected more from this director.",
            "சூப்பர் ஹிட்! விஜய் அசத்தினார்! 💯",
            "Average movie with some good moments.",
            "Worst movie ever watched! 😡",
            "Loved the music and bgm! Rahman magic! 🎵",
            "Mixed feelings - good scenes but weak story.",
            "படம் நன்றாக இருந்தது! விஜய் நடிப்பு அற்புதம்!",
            "Time waste! Don't watch this movie",
            "Super movie! Must watch in theaters",
            "சுமாரான திரைப்படம், சில நல்ல காட்சிகள்",
            "Very boring, couldn't finish watching"
        ],
        'label': ['positive', 'neutral', 'negative', 'positive', 'neutral',
                  'positive', 'neutral', 'negative', 'positive', 'neutral',
                  'positive', 'negative', 'positive', 'neutral', 'negative']
    }

    clean_df = pd.DataFrame(synthetic_data)
    print(f"Synthetic dataset created with {len(clean_df)} samples")

import emoji
from bs4 import BeautifulSoup

def clean_tamil_english_text(text):
    """
    Clean Tamil-English code-mixed text
    """
    if not isinstance(text, str):
        return ""

    # Convert to string
    text = str(text)

    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()

    # Convert emojis to text
    text = emoji.demojize(text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove user mentions and hashtags (keep the text after #)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#', '', text)

    # Remove special characters but keep Tamil and English characters
    # Tamil Unicode range: \u0B80-\u0BFF
    text = re.sub(r'[^\w\s\u0B80-\u0BFF.,!?]', ' ', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Convert multiple dots to single dot
    text = re.sub(r'\.{2,}', '.', text)

    return text.lower()

# Step 9: Apply cleaning to clean_df
print("\nApplying text cleaning...")
clean_df['cleaned_text'] = clean_df['text'].apply(clean_tamil_english_text)

# Remove empty texts after cleaning
initial_count = len(clean_df)
clean_df = clean_df[clean_df['cleaned_text'].str.strip() != '']
final_count = len(clean_df)

print(f"Removed {initial_count - final_count} empty texts after cleaning")
print(f"Final dataset size: {final_count}")

# Show before/after cleaning
print("\nText cleaning examples:")
for i in range(min(3, len(clean_df))):
    print(f"\nExample {i+1}:")
    print(f"Original: {clean_df.iloc[i]['text']}")
    print(f"Cleaned: {clean_df.iloc[i]['cleaned_text']}")
    print("-" * 50)

from sklearn.preprocessing import LabelEncoder

# First, let's see unique labels
print("\nUnique labels before encoding:")
print(clean_df['label'].unique())

# Map to standard labels
label_mapping = {
    'positive': 'positive',
    'pos': 'positive',
    'Positive': 'positive',
    'POSITIVE': 'positive',
    'negative': 'negative',
    'neg': 'negative',
    'Negative': 'negative',
    'NEGATIVE': 'negative',
    'neutral': 'neutral',
    'neu': 'neutral',
    'Neutral': 'neutral',
    'NEUTRAL': 'neutral',
    'mixed': 'neutral',
    'Mixed': 'neutral',
    'not_offensive': 'neutral',
    'not offensive': 'neutral',
    'offensive': 'negative'
}

clean_df['standardized_label'] = clean_df['label'].str.lower().map(label_mapping)

# For any unmapped labels, use the original
clean_df['standardized_label'] = clean_df['standardized_label'].fillna(clean_df['label'].str.lower())

print("\nUnique labels after standardization:")
print(clean_df['standardized_label'].unique())

# Encode labels
label_encoder = LabelEncoder()
clean_df['encoded_label'] = label_encoder.fit_transform(clean_df['standardized_label'])

print("\nLabel mapping:")
for i, label in enumerate(label_encoder.classes_):
    print(f"{label}: {i}")

print(f"\nLabel distribution:")
print(clean_df['standardized_label'].value_counts())

# See the top 20 most frequent raw labels
print(clean_df['label'].value_counts().head(20))

def group_labels(label):
    label = str(label).lower().strip()
    if any(word in label for word in ['pos', 'happy', 'good', 'joy']):
        return 'positive'
    if any(word in label for word in ['neg', 'bad', 'hate', 'angry', 'offensive']):
        return 'negative'
    if any(word in label for word in ['mixed', 'ambiguous']):
        return 'mixed'
    return 'neutral' # Default to neutral

# Apply the grouping
clean_df['standardized_label'] = clean_df['label'].apply(group_labels)

# Now check the counts again - it should be much smaller (3-5 classes)
print(clean_df['standardized_label'].value_counts())

# Now Re-encode
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
clean_df['encoded_label'] = le.fit_transform(clean_df['standardized_label'])

from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    clean_df['cleaned_text'],
    clean_df['encoded_label'],
    test_size=0.2,
    random_state=42,
    stratify=clean_df['encoded_label']
)

print(f"Success! You now have {len(le.classes_)} classes.")

import torch

class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):
        # Extracts input_ids and attention_mask for the model
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        # Adds the target sentiment label
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

print("✅ SentimentDataset class defined successfully.")

from sklearn.metrics import accuracy_score, f1_score
import numpy as np

def compute_metrics(eval_pred):
    """
    Standard research function for Hugging Face Trainer.
    Calculates both raw Accuracy and Macro F1-score.
    """
    logits, labels = eval_pred
    # Convert model probabilities (logits) to specific class predictions
    predictions = np.argmax(logits, axis=-1)

    # Calculate metrics
    acc = accuracy_score(labels, predictions)
    # 'macro' average treats all classes equally, which is the research standard
    f1 = f1_score(labels, predictions, average='macro')

    return {
        'accuracy': acc,
        'f1': f1
    }

print("✅ compute_metrics defined. Ready for training.")

# Now run this - it should work without error!
results_mbert = train_and_evaluate("bert-base-multilingual-cased")

print("\n--- mBERT FINAL RESULTS ---")
print(results_mbert)

# Now run the benchmark for the second model
# This allows you to say "I compared multiple SOTA architectures" in your resume
results_xlmr = train_and_evaluate("xlm-roberta-base")

print("\n--- COMPARATIVE RESEARCH REPORT ---")
print(f"mBERT Accuracy: {results_mbert['eval_accuracy']:.4f} | F1: {results_mbert['eval_f1']:.4f}")
print(f"XLM-R Accuracy: {results_xlmr['eval_accuracy']:.4f} | F1: {results_xlmr['eval_f1']:.4f}")

import numpy as np
from statsmodels.stats.contingency_tables import mcnemar

def perform_mcnemar(trainer_a, trainer_b, dataset):
    # Get predictions
    preds_a = np.argmax(trainer_a.predict(dataset).predictions, axis=-1)
    preds_b = np.argmax(trainer_b.predict(dataset).predictions, axis=-1)

    # Get ground truth safely
    if hasattr(dataset, "labels"):
        ground_truth = np.array(dataset.labels)
    elif hasattr(dataset, "label_ids"):
        ground_truth = np.array(dataset.label_ids)
    else:
        raise AttributeError("Dataset must contain 'labels' or 'label_ids'")

    # Ensure same length
    min_len = min(len(preds_a), len(preds_b), len(ground_truth))
    preds_a = preds_a[:min_len]
    preds_b = preds_b[:min_len]
    ground_truth = ground_truth[:min_len]

    # Correctness masks
    a_right = preds_a == ground_truth
    b_right = preds_b == ground_truth

    # McNemar contingency table
    table = np.array([
        [np.sum(a_right & b_right), np.sum(a_right & ~b_right)],
        [np.sum(~a_right & b_right), np.sum(~a_right & ~b_right)]
    ])

    print("Contingency Table:\n", table)

    # Run McNemar test
    result = mcnemar(table, exact=True)

    print(f"McNemar's Test Statistic: {result.statistic}")
    print(f"McNemar's Test p-value: {result.pvalue:.6f}")

    if result.pvalue < 0.05:
        print("Result is Statistically Significant")
    else:
        print("Result is NOT Statistically Significant")